#ifndef QBIT_CHAINPARAMSSEEDS_H
#define QBIT_CHAINPARAMSSEEDS_H
#include <array>
#include <cstdint>

/**
 * List of fixed seed nodes for the qbit network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static constexpr std::array<uint8_t, 0> chainparams_seed_main{{
}};

static constexpr std::array<uint8_t, 0> chainparams_seed_signet{{
}};

static constexpr std::array<uint8_t, 0> chainparams_seed_test{{
}};

static constexpr std::array<uint8_t, 16> chainparams_seed_testnet4{{
    0x01,0x04,0x39,0x81,0x56,0x3d,0xbc,0xe3,
    0x01,0x04,0x28,0xa0,0x42,0xc4,0xbc,0xe3,
}};
#endif // QBIT_CHAINPARAMSSEEDS_H
