description "qbit Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env QBITD_BIN="/usr/bin/qbitd"
env QBITD_USER="qbit"
env QBITD_GROUP="qbit"
env QBITD_PIDDIR="/run/qbit"
# upstart can't handle variables constructed with other variables
env QBITD_PIDFILE="/run/qbit/qbitd.pid"
env QBITD_CONFIGFILE="/etc/qbit/qbit.conf"
env QBITD_DATADIR="/var/lib/qbit"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # qbitd will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$QBITD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run qbitd."
        echo "The setting must appear in $QBITD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"qbit Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$QBITD_PIDDIR"
    chmod 0755 "$QBITD_PIDDIR"
    chown $QBITD_USER:$QBITD_GROUP "$QBITD_PIDDIR"
    chown $QBITD_USER:$QBITD_GROUP "$QBITD_CONFIGFILE"
    chmod 0660 "$QBITD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$QBITD_PIDFILE" \
    --chuid $QBITD_USER:$QBITD_GROUP \
    --exec "$QBITD_BIN" \
    -- \
    -pid="$QBITD_PIDFILE" \
    -conf="$QBITD_CONFIGFILE" \
    -datadir="$QBITD_DATADIR" \
    -disablewallet \
    -daemon
